---

version: '3'

volumes:
  swordphish_data:

services:
  swordphish:
    container_name: swordphish_main
    image: swordphish
    ports:
      - "8000:8000"
    links:
      - swordphish-redis
      - swordphish-postgres
      - swordphish-mail
    restart: always
  swordphish-redis:
    image: redis:latest
  swordphish-beat:
    image: swordphish
    links:
      - swordphish-redis
      - swordphish-postgres
      - swordphish-mail
    command: ['docker-entrypoint.sh', 'beat']
    restart: always
  swordphish-worker:
    image: swordphish
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    links:
      - swordphish-redis
      - swordphish-postgres
      - swordphish-mail
    command: ['docker-entrypoint.sh', 'workers']
    restart: always
  swordphish-mail:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
    restart: always
  swordphish-postgres:
    image: postgres:latest
    volumes:
    - swordphish_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=swordphish
      - POSTGRES_PASSWORD=swordphish
      - POSTGRES_DB=swordphish
    restart: always
